# Generated by Django 4.2 on 2025-04-16 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_addservide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddServide',
            new_name='AddService',
        ),
    ]
