# Generated by Django 4.2 on 2025-04-18 04:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_rename_addservide_addservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddService',
            new_name='Service',
        ),
    ]
