# Generated by Django 4.2 on 2025-04-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_servicecategory_created_on_and_more'),
        ('api', '0004_rename_addservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_description',
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.servicecategory'),
        ),
    ]
