# Generated by Django 4.2 on 2025-04-18 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_service_service_description_service_service_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='tbl_service',
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_status', models.CharField(default='Pending', max_length=50)),
                ('service_date', models.DateTimeField(blank=True, null=True)),
                ('service_time', models.TimeField(blank=True, null=True)),
                ('service_address', models.TextField(blank=True, null=True)),
                ('service_rating', models.IntegerField(blank=True, null=True)),
                ('service_review', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
            options={
                'db_table': 'tbl_service_booking',
                'managed': True,
            },
        ),
    ]
