# Generated by Django 4.2 on 2025-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_service_table_servicebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
