# Generated by Django 4.2 on 2025-04-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderinfo',
            name='break_status',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
