# Generated by Django 4.2 on 2025-04-17 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
